# Source: cluster-api-aws/templates/job-pre-delete.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: cr7h8ef92-capi-aws-pre-delete
  namespace: cr7h8ef92
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      name: cr7h8ef92-capi-aws
    spec:
      serviceAccountName: cr7h8ef92-capi-aws
      containers:
      - name: delete-mp
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout
        - 20m
        - /delete_from_yaml_raw.py
        - mp.raw.yaml
        volumeMounts:
        - name: vol
          subPath: mp.raw.yaml
          mountPath: /mp.raw.yaml
        - name: vol
          subPath: delete_from_yaml_raw.py
          mountPath: /delete_from_yaml_raw.py
      - name: delete-md
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout
        - 20m
        - /delete_from_yaml_raw.py
        - md.raw.yaml
        volumeMounts:
        - name: vol
          subPath: md.raw.yaml
          mountPath: /md.raw.yaml
        - name: vol
          subPath: delete_from_yaml_raw.py
          mountPath: /delete_from_yaml_raw.py

      volumes:
      - name: vol
        configMap:
          name: cr7h8ef92-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure

