# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "lma"
  labels:
    app: minio
    chart: minio-7.0.0
    release: minio
    heritage: Helm
type: Opaque
data:
  rootUser: "TFE5U2lFRHFrRlNsYmdYVTI5WWo="
  rootPassword: "QUZUS3NlbFZaUEt4dlZxNnZFbWRJeE5IOEpnbzhhcUprNmtoS0NKWA=="
